apiVersion: v1
kind: Pod
metadata:
    name: udacity-projects
    # namespace: python
    labels:
        app: udacity
        app.kubernetes.io/name: app
        app.kubernetes.io/instance: python3
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/component: webapp
        environment: qa
spec:
    containers:
        - name: udacity-projects
          image: nabisco83/devops-training-machine-learning:completed
          imagePullPolicy: Always
          # command: ["echo", "SUCCESS"]
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: udacity-projects-service
    labels:
        app: udacity
spec:
    type: NodePort
    selector: 
        app: udacity
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 80